version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    
    command: >
      sh -c "
          python manage.py wait_for_db &&
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000
      "
    
    stdin_open: true
    
    tty: true
    
    depends_on:
      - db
  db :
    image: postgres:10-alpine
    env_file:
      - ./database.env
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql  
  

# volumes:
#   dbData:
