version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend.env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    stdin_open: true
    
    tty: true
    
  #   depends_on:
  #     - db
  # db:
  #   image: imageName